project:
  type: website
  output-dir: docs

website:
  title: "Madeleine's Epic Open Science and Computing Blog"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    title-block-banner: img/mountains.jpg
    title-block-banner-color: white
    theme: sandstone
    css: styles.css
