project:
  type: website
  output-dir: /docs

website:
  title: "My Awesome CSCI 0451 Blog"
  output-dir: /docs
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    title-block-banner: img/landscape.png
    title-block-banner-color: white
    theme: morph
    css: styles.css





